<?php
/*
 * This file is part of MODX Revolution.
 *
 * Copyright (c) MODX, LLC. All Rights Reserved.
 *
 * For complete copyright and license information, see the COPYRIGHT and LICENSE
 * files found in the top-level directory of this distribution.
 */

require_once MODX_CORE_PATH.'model/modx/processors/element/snippet/getlist.class.php';

class CronTabManagerSnippetGetListProcessor extends modSnippetGetListProcessor
{
    public $classKey = 'modSnippet';
    public $languageTopics = array('snippet', 'category', 'crontabmanager:manager');
    public $permission = 'view_snippet';

    public function prepareQueryBeforeCount(xPDOQuery $c)
    {
        $query = trim($this->getProperty('query'));
        if (!empty($query)) {
            $c->where(array(
                'name:LIKE' => '%'.$query.'%',
            ));
        }

        return parent::prepareQueryBeforeCount($c); // TODO: Change the autogenerated stub
    }

    public function outputArray(array $array, $count = false)
    {
        foreach ($array as $key => $item) {
            if (empty($item['description'])) {
                $array[$key]['description'] = '';
            } else {
                $array[$key]['description'] = ' - '.$item['description'];
            }
        }

        if ($this->getProperty('addall')) {
            $array = array_merge_recursive(array(
                array(
                    'name' => $this->modx->lexicon('crontabmanager_snippet_all'),
                    'value' => 0,
                    'description' => '',
                ),
            ), $array);
        }


        return parent::outputArray($array, $count); // TODO: Change the autogenerated stub
    }
}

return 'CronTabManagerSnippetGetListProcessor';
