<?php

include_once dirname(__FILE__, 4).'/bootstrap.php';

class Style extends \Symfony\Component\Console\Style\SymfonyStyle
{
    public function block($messages, string $type = null, string $style = null, string $prefix = ' ', bool $padding = false, bool $escape = true)
    {
        $escape = true;
        $prefix = '';
        $padding = false;
        parent::block($messages, $type, $style, $prefix, $padding, $escape); // TODO: Change the autogenerated stub
    }
}
